#ifndef FOOTPRINTEDITOR_GLOBAL_H
#define FOOTPRINTEDITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FOOTPRINTEDITOR_LIBRARY)
#  define FOOTPRINTEDITORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FOOTPRINTEDITORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FOOTPRINTEDITOR_GLOBAL_H
